spring:
  application:
    name: community_blog
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/community?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  thymeleaf:
    cache: false
  mail:
    host: smtp.sina.com
    port: 465
    username: jiashuhuang@sina.com
    password:  #授权码而不是真实密码
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  cache:
    redis:
      time-to-live: 1800000 #缓存数据过期时间
  redis:
    database: 2
    host: localhost
    port: 6379
community:
  path:
    domain: http://localhost:8080
    img: D:/Harry/Dark-Horse/Projects/community_blog/img
    postPage: /discussPost/index
    commentPage: /discussPost/detail/
    messagePage: /message/page
    messageDetailPage: /message/detail/
mybatis-plus:
  mapper-locations: classpath:mapper/**.xml
  type-aliases-package: com.community_blog.domain